microserviceName: "catalog"

image:
  repository: acrpfpos.azurecr.io/play.catalog
  tag : 1.0.0

envVariables:
  ServiceSettings__Authority: https://gameplayeconomy.com/identity-svc

container:
  port: 5000

identityClientId: e5986e8a-4817-40fc-b961-333d51586bd0
    